set nocompatible

" Install plugins
source $HOME/.vim/plug.vim

" Vim Options
set backspace=indent,eol,start
set clipboard=unnamed   "set the \"* register to the clipboard
set clipboard=unnamedplus   "set the \"+ register to the clipboard
set number	" show line number
set shiftwidth=4        " size of an indent
set smarttab	" make 'tab' inset indents instead of tabs
set tabstop=4	" size of hard tab stop
set softtabstop=4
set expandtab	" always use spaces instead of tab characters
set encoding=utf-8
set modelines=0
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set ruler
set laststatus=2
"set relativenumber
set undofile
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=2

" Fix vim default regex searching
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch

" Handle long lines
set wrap
set textwidth=80
set formatoptions=qrn1
set colorcolumn=100
hi ColorColumn ctermbg=7

syntax on

filetype off
filetype plugin indent on       " required
runtime macros/matchit.vim

" Global Options
let g:go_disable_autoinstall = 0
let g:neocomplete#enable_at_startup = 1
set wildignore+=.*

" Vim-Airline settings
let g:airline#extensions#tabline#enabled = 1	" enable the list of buffers
let g:airline#extensions#tabline#fnamemod = ':t'	" show just the filename

" CtrlP settings
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'
"let g:ctrlp_user_command = 'find %s -type f' 	" custom file listing command
let g:ctrlp_custom_ignore = {
  \ 'dir': '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(o|so|swp|pyc|class)$'
  \}

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_loc_list_height = 5

" Signify
let g:signify_vcs_list = [ 'hg', 'svn' ]

" YouCompleteMe
let g:ycm_min_num_of_chars_for_completion = 10
let g:ycm_autoclose_preview_window_after_completion = 1

" KEY Mappings 
""""""""""""""""
let mapleader = ";"

nnoremap W :w<cr>

" clear highlights
nnoremap <leader><space> :noh<cr>
" toggle nerd tree
map <c-n> :NERDTreeToggle<CR>
" toggle ctrl-p
map <c-p> :CtrlP<CR>
" map Ctrl-c to copy to clipboard
vnoremap <c-c> "+y
" map <leader>g to jump to definition
nnoremap <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>
" toggle syntastic
nnoremap <leader>sc :SyntasticCheck
nnoremap <leader>sr :SyntasticReset

colorscheme dracula

